"""Frozen, condition-blind scientific metrics.

Metric modules consume validated projections and scorer-side anchor records.  They
never participate in generation and never expose scorer labels to a condition.
"""

from .adapters import (
    ProjectionMetricAdapter,
    adapt_projection_for_metrics,
    normalize_projection_decisions,
    verify_normalized_decisions,
    verify_projection_decisions,
)
from .alignment import (
    AlignmentPlan,
    AlignmentResult,
    OntologyDecisionScore,
    audit_qualified_assertion_grounding,
    score_alignment,
    score_ontology_decisions,
)
from .common import PrecisionRecallF1
from .config import StudyMetricConfiguration
from .contrastive import (
    ContrastInvariantScore,
    ContrastiveCollapseSummary,
    ContrastiveScore,
    ParaphraseStabilityScore,
    aggregate_contrastive_collapse,
    score_contrast_invariants,
    score_contrastive_changes,
    score_paraphrase_stability,
)
from .decision_states import (
    DECISION_STATE_COMPILER_REVISION,
    DecisionCompilationIssue,
    DecisionStateCompilation,
    InvariantCompilationIssue,
    compile_and_verify_decision_states,
    compile_gold_contrast_invariants,
    compile_gold_decision_targets,
    compile_projection_assertion_semantics,
)
from .pipeline import (
    CommunityMetricPanel,
    CompleteProjectionScoreBundle,
    ContrastMetricPlan,
    ContrastPairScore,
    CrossSeedCommunityScore,
    FailedMetricOutput,
    GeometryMetricInput,
    GroundingAuditInput,
    IntendedMetricManifest,
    IntendedMetricUnit,
    IntendedUnitScore,
    MetricResultRow,
    OutputFailureKind,
    PipelineMetricStatus,
    ProjectionScoreBundle,
    ScorerMetricPlan,
    StructuralMetricPanel,
    analysis_observations_from_scores,
    load_intended_unit_scores,
    load_intended_unit_scores_from_metric_records,
    materialize_intention_to_treat_scores,
    persist_intended_unit_score,
    persist_metric_rows,
    score_complete_projection,
    score_contrast_pair,
    score_cross_seed_community,
    score_failed_output,
    score_intended_projection,
    score_projection,
    validate_intended_unit_manifest,
)
from .rare import RarePivotalScore, score_rare_pivotal

__all__ = [
    "DECISION_STATE_COMPILER_REVISION",
    "AlignmentPlan",
    "AlignmentResult",
    "CommunityMetricPanel",
    "CompleteProjectionScoreBundle",
    "ContrastInvariantScore",
    "ContrastMetricPlan",
    "ContrastPairScore",
    "ContrastiveCollapseSummary",
    "ContrastiveScore",
    "CrossSeedCommunityScore",
    "DecisionCompilationIssue",
    "DecisionStateCompilation",
    "FailedMetricOutput",
    "GeometryMetricInput",
    "GroundingAuditInput",
    "IntendedMetricManifest",
    "IntendedMetricUnit",
    "IntendedUnitScore",
    "InvariantCompilationIssue",
    "MetricResultRow",
    "OntologyDecisionScore",
    "OutputFailureKind",
    "ParaphraseStabilityScore",
    "PipelineMetricStatus",
    "PrecisionRecallF1",
    "ProjectionMetricAdapter",
    "ProjectionScoreBundle",
    "RarePivotalScore",
    "ScorerMetricPlan",
    "StructuralMetricPanel",
    "StudyMetricConfiguration",
    "adapt_projection_for_metrics",
    "aggregate_contrastive_collapse",
    "analysis_observations_from_scores",
    "audit_qualified_assertion_grounding",
    "compile_and_verify_decision_states",
    "compile_gold_contrast_invariants",
    "compile_gold_decision_targets",
    "compile_projection_assertion_semantics",
    "load_intended_unit_scores",
    "load_intended_unit_scores_from_metric_records",
    "materialize_intention_to_treat_scores",
    "normalize_projection_decisions",
    "persist_intended_unit_score",
    "persist_metric_rows",
    "score_alignment",
    "score_complete_projection",
    "score_contrast_invariants",
    "score_contrast_pair",
    "score_contrastive_changes",
    "score_cross_seed_community",
    "score_failed_output",
    "score_intended_projection",
    "score_ontology_decisions",
    "score_paraphrase_stability",
    "score_projection",
    "score_rare_pivotal",
    "validate_intended_unit_manifest",
    "verify_normalized_decisions",
    "verify_projection_decisions",
]
